[env:m5stack-cardputer]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
board_build.partitions = default_8MB.csv
board_build.filesystem = littlefs
lib_deps = 
	m5stack/M5Cardputer @ 1.1.1
	m5stack/M5Unified @ ^0.2.15
	bblanchon/ArduinoJson @ ^7.0.4
	mathieucarbou/ESPAsyncWebServer @ ^3.1.5
	adafruit/Adafruit NeoPixel @ ^1.12.0
